### ISSUE TITLE
Consider GPLv2+ license

### ISSUE THREAD

**Issue by JayFoxRox** [akopetsch/swracer-assets#5]
The license proposal for this repository is the GPLv3. However, that license is incompatible with the GPLv2, and there's still lots of software that is containing GPLv2-only code.

OpenSWE1R might share code with this project in the future, but it depends on Unicorn. Unicorn is forked from QEMU and therefore depends on GPLv2-only code.
While there are configurations of OpenSWE1R which can avoid such GPLv2-only code, there might be other affected code in the future. Also the GPLv2-only build is the only build which is truely cross-platform.

So as it stands, we couldn't easily share code if necessary.
While there are currently language barriers between C, C++, C#, who knows what the future might hold.

A possible solution to this problem would be to use the "GPLv2 or later" license.
Re-licensing early on is the preferred option before contributors might be unreachable for getting a permission (OpenSWE1R uses a CLA to deal with this).

**Comment by akopetsch** [comment]
I just changed the LICENSE from GPLv3 to GPLv2 (before adding the actual source code files) to ensure the compatibility with OpenSWE1R.

**Comment by JayFoxRox** [comment]
Make sure you are explicit about being GPLv2+ (meaning GPLv2 *or later*). That's the best way to make sure the code is re-usable with most other projects. Other licenses would be even better, but GPLv2+ is probably the best I can ask for if your intention is to stick with the GPL :)
